name: Linux C++ make-specs
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
      extra_test_command:
        description: "Extra Test Command"
        type: string
        required: false
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
  EXTRA_TEST_COMMAND: ${{ github.event.inputs.extra_test_command }}
jobs:
  docker_builds:
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: ghcr.io/steinwurf/gcc-11.2.0:1.0.0
            cxx_mkspec: --cxx_mkspec=cxx_gxx112_x64
            name: GCC 11.2
          - container: ghcr.io/steinwurf/gcc-6.3.0:1.0.0
            cxx_mkspec: --cxx_mkspec=cxx_gxx63_x64
            name: GCC 6.3
          - container: ghcr.io/steinwurf/clang-3.9:1.0.0
            name: Clang 3.9
            cxx_mkspec: --cxx_mkspec=cxx_clang39_x64
          - container: ghcr.io/steinwurf/clang-13:1.0.0
            name: Clang 13
            cxx_mkspec: --cxx_mkspec=cxx_clang130_x64
          - container: ghcr.io/steinwurf/clang-13:1.0.0
            cxx_mkspec: --cxx_mkspec=cxx_clang13_address_sanitizer_x64
            name: Clang 13 Address Sanitizer
          # TODO: Re-able this when we have fixed memory issue in google-test
          # - container: steinwurf/clang:13
          #   cxx_mkspec: --cxx_mkspec=cxx_clang13_memory_sanitizer_x64
          #   name: Clang 13 Memory Sanitizer
          - container: ghcr.io/steinwurf/clang-13:1.0.0
            cxx_mkspec: --cxx_mkspec=cxx_clang13_thread_sanitizer_x64
            name: Clang 13 Thread Sanitizer
    runs-on: [self-hosted, docker, builder]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Waf Configure
        run: python3 waf configure --git_protocol=git@ ${{ matrix.config.cxx_mkspec }} $EXTRA_RESOLVE_OPTIONS
      - name: Waf Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Waf Test
        run: python3 waf --run_tests --run_cmd="%s $(( $EXTRA_TEST_COMMAND ))"
